pendulum:
    start_cartx: 0
    start_angle: 1
    track_length: 1.5
    simulation:
        cart_friction: 0.1
        delta_time: 0.01
        gravity: 9.81
        pole_friction: 0.1
        mass: 1.0
        pole_length: 1.0
    pid:
        update_frequency: 10
        angle:
            p: 4
            i: 0.0
            d: 1
        cart:
            p: -10
            i: 0.0
            d: 10

