pendulum:
    start_cartx: 0
    start_angle: 0
    track_length: 2
    simulation:
        cart_friction: 0.1
        delta_time: 0.01
        gravity: 9.81
        pole_friction: 0.1
        mass: 1.0
        pole_length: 1.0

